### ISSUE TITLE
 Class "Webkul\Core\Providers\BaseModuleServiceProvider" not found

### ISSUE THREAD

**Issue by SanghangSH** [krayin/krayin-google-integration#44]
Class "Webkul\Core\Providers\BaseModuleServiceProvider" not found

  at C:\wamp64\www\MJQ\ConnectGoogleCalendar\vendor\krayin\krayin-google-integration\src\Providers\ModuleServiceProvider.php:7
      3▕ namespace Webkul\Google\Providers;
      4▕
      5▕ use Webkul\Core\Providers\BaseModuleServiceProvider;
      6▕
  ➜   7▕ class ModuleServiceProvider extends BaseModuleServiceProvider
      8▕ {
      9▕     protected $models = [
     10▕         \Webkul\Google\Models\Account::class,
     11▕         \Webkul\Google\Models\Calendar::class,

  1   C:\wamp64\www\MJQ\ConnectGoogleCalendar\vendor\composer\ClassLoader.php:571
      include()

  2   C:\wamp64\www\MJQ\ConnectGoogleCalendar\vendor\composer\ClassLoader.php:428

**Comment by Hiteshsutharrr** [comment]
did you found any solution ?

**Comment by karan-nukani** [comment]
Error

  Class "Webkul\Core\Providers\BaseModuleServiceProvider" not found

  at C:\xampp\htdocs\inventory-test\vendor\krayin\krayin-google-integration\src\Providers\ModuleServiceProvider.php:7
      3▕ namespace Webkul\Google\Providers;
      4▕
      5▕ use Webkul\Core\Providers\BaseModuleServiceProvider;
      6▕
  ➜   7▕ class ModuleServiceProvider extends BaseModuleServiceProvider
      8▕ {
      9▕     protected $models = [
     10▕         \Webkul\Google\Models\Account::class,
     11▕         \Webkul\Google\Models\Calendar::class,

   Whoops\Exception\ErrorException

  Using ${var} in strings is deprecated, use {$var} instead

  at C:\xampp\htdocs\inventory-test\vendor\facade\ignition\src\SolutionProviders\MergeConflictSolutionProvider.php:52
     48▕     }
     49▕
     50▕     protected function getCurrentBranch(string $directory): string
     51▕     {
  ➜  52▕         $branch = "'".trim(shell_exec("cd ${directory}; git branch | grep \\* | cut -d ' ' -f2"))."'";
     53▕
     54▕         if ($branch === "''") {
     55▕             $branch = 'current branch';
     56▕         }

   Symfony\Component\ErrorHandler\Error\FatalError

  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in C:\xampp\htdocs\inventory-test\vendor\facade\ignition\src\SolutionProviders\MergeConflictSolutionProvider.php:52
Stack trace:
#0 C:\xampp\htdocs\inventory-test\vendor\composer\ClassLoader.php(582): Whoops\Run->handleError(8192, 'Using ${var} in...', 'C:\\xampp\\htdocs...', 52)   
#1 C:\xampp\htdocs\inventory-test\vendor\composer\ClassLoader.php(582): include()
#2 C:\xampp\htdocs\inventory-test\vendor\composer\ClassLoader.php(433): Composer\Autoload\{closure}('C:\\xampp\\htdocs...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Facade\\Ignition...')
#4 C:\xampp\htdocs\inventory-test\vendor\facade\ignition\src\SolutionProviders\SolutionProviderRepository.php(50): class_implements('Facade\\Ignition...')
#5 [internal function]: Facade\Ignition\SolutionProviders\SolutionProviderRepository->Facade\Ignition\SolutionProviders\{closure}('Facade\\Ignition...', 10)
#6 C:\xampp\htdocs\inventory-test\vendor\laravel\framework\src\Illuminate\Collections\Arr.php(717): array_filter(Array, Object(Closure), 1)
#7 C:\xampp\htdocs\inventory-test\vendor\laravel\framework\src\Illuminate\Collections\Collection.php(358): Illuminate\Support\Arr::where(Array, Object(Closure))
#8 C:\xampp\htdocs\inventory-test\vendor\facade\ignition\src\SolutionProviders\SolutionProviderRepository.php(49): Illuminate\Support\Collection->filter(Object(Closure))
#9 C:\xampp\htdocs\inventory-test\vendor\nunomaduro\collision\src\Adapters\Laravel\IgnitionSolutionsRepository.php(36): Facade\Ignition\SolutionProviders\SolutionProviderRepository->getSolutionsForThrowable(Object(Whoops\Exception\ErrorException))
#10 C:\xampp\htdocs\inventory-test\vendor\nunomaduro\collision\src\Writer.php(244): NunoMaduro\Collision\Adapters\Laravel\IgnitionSolutionsRepository->getFromThrowable(Object(Whoops\Exception\ErrorException))
#11 C:\xampp\htdocs\inventory-test\vendor\nunomaduro\collision\src\Writer.php(123): NunoMaduro\Collision\Writer->renderSolution(Object(Whoops\Exception\Inspector))
#12 C:\xampp\htdocs\inventory-test\vendor\nunomaduro\collision\src\Handler.php(39): NunoMaduro\Collision\Writer->write(Object(Whoops\Exception\Inspector))
#13 C:\xampp\htdocs\inventory-test\vendor\filp\whoops\src\Whoops\Run.php(370): NunoMaduro\Collision\Handler->handle(Object(Whoops\Exception\ErrorException))
#14 [internal function]: Whoops\Run->handleException(Object(Whoops\Exception\ErrorException))
#15 {main}
  thrown

  at C:\xampp\htdocs\inventory-test\vendor\facade\ignition\src\SolutionProviders\MergeConflictSolutionProvider.php:52
     48▕     }
     49▕
     50▕     protected function getCurrentBranch(string $directory): string
     51▕     {
  ➜  52▕         $branch = "'".trim(shell_exec("cd ${directory}; git branch | grep \\* | cut -d ' ' -f2"))."'";
     53▕
     54▕         if ($branch === "''") {
     55▕             $branch = 'current branch';
     56▕         }
PHP Fatal error:  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in C:\xampp\htdocs\inventory-test\vendor\facade\ignition\src\SolutionProviders\MergeConflictSolutionProvider.php:52
Stack trace:
#0 C:\xampp\htdocs\inventory-test\vendor\composer\ClassLoader.php(582): Whoops\Run->handleError(8192, 'Using ${var} in...', 'C:\\xampp\\htdocs...', 52)   
#1 C:\xampp\htdocs\inventory-test\vendor\composer\ClassLoader.php(582): include()
#2 C:\xampp\htdocs\inventory-test\vendor\composer\ClassLoader.php(433): Composer\Autoload\{closure}('C:\\xampp\\htdocs...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Facade\\Ignition...')
#4 C:\xampp\htdocs\inventory-test\vendor\facade\ignition\src\SolutionProviders\SolutionProviderRepository.php(50): class_implements('Facade\\Ignition...')
#5 [internal function]: Facade\Ignition\SolutionProviders\SolutionProviderRepository->Facade\Ignition\SolutionProviders\{closure}('Facade\\Ignition...', 10)
#6 C:\xampp\htdocs\inventory-test\vendor\laravel\framework\src\Illuminate\Collections\Arr.php(717): array_filter(Array, Object(Closure), 1)
#7 C:\xampp\htdocs\inventory-test\vendor\laravel\framework\src\Illuminate\Collections\Collection.php(358): Illuminate\Support\Arr::where(Array, Object(Closure))
#8 C:\xampp\htdocs\inventory-test\vendor\facade\ignition\src\SolutionProviders\SolutionProviderRepository.php(49): Illuminate\Support\Collection->filter(Object(Closure))
#9 C:\xampp\htdocs\inventory-test\vendor\nunomaduro\collision\src\Adapters\Laravel\IgnitionSolutionsRepository.php(36): Facade\Ignition\SolutionProviders\SolutionProviderRepository->getSolutionsForThrowable(Object(Whoops\Exception\ErrorException))
#10 C:\xampp\htdocs\inventory-test\vendor\nunomaduro\collision\src\Writer.php(244): NunoMaduro\Collision\Adapters\Laravel\IgnitionSolutionsRepository->getFromThrowable(Object(Whoops\Exception\ErrorException))
#11 C:\xampp\htdocs\inventory-test\vendor\nunomaduro\collision\src\Writer.php(123): NunoMaduro\Collision\Writer->renderSolution(Object(Whoops\Exception\Inspector))
#12 C:\xampp\htdocs\inventory-test\vendor\nunomaduro\collision\src\Handler.php(39): NunoMaduro\Collision\Writer->write(Object(Whoops\Exception\Inspector))
#13 C:\xampp\htdocs\inventory-test\vendor\filp\whoops\src\Whoops\Run.php(370): NunoMaduro\Collision\Handler->handle(Object(Whoops\Exception\ErrorException))
#14 [internal function]: Whoops\Run->handleException(Object(Whoops\Exception\ErrorException))
#15 {main}
  thrown in C:\xampp\htdocs\inventory-test\vendor\facade\ignition\src\SolutionProviders\MergeConflictSolutionProvider.php on line 52
PHP Fatal error:  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in C:\xampp\htdocs\inventory-test\vendor\facade\ignition\src\SolutionProviders\MergeConflictSolutionProvider.php:52
Stack trace:
#0 C:\xampp\htdocs\inventory-test\vendor\composer\ClassLoader.php(582): Whoops\Run->handleError(8192, 'Using ${var} in...', 'C:\\xampp\\htdocs...', 52)   
#1 C:\xampp\htdocs\inventory-test\vendor\composer\ClassLoader.php(582): include()
#2 C:\xampp\htdocs\inventory-test\vendor\composer\ClassLoader.php(433): Composer\Autoload\{closure}('C:\\xampp\\htdocs...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Facade\\Ignition...')
#4 C:\xampp\htdocs\inventory-test\vendor\facade\ignition\src\SolutionProviders\SolutionProviderRepository.php(50): class_implements('Facade\\Ignition...')
#5 [internal function]: Facade\Ignition\SolutionProviders\SolutionProviderRepository->Facade\Ignition\SolutionProviders\{closure}('Facade\\Ignition...', 10)
#6 C:\xampp\htdocs\inventory-test\vendor\laravel\framework\src\Illuminate\Collections\Arr.php(717): array_filter(Array, Object(Closure), 1)
#7 C:\xampp\htdocs\inventory-test\vendor\laravel\framework\src\Illuminate\Collections\Collection.php(358): Illuminate\Support\Arr::where(Array, Object(Closure))
#8 C:\xampp\htdocs\inventory-test\vendor\facade\ignition\src\SolutionProviders\SolutionProviderRepository.php(49): Illuminate\Support\Collection->filter(Object(Closure))
#9 C:\xampp\htdocs\inventory-test\vendor\nunomaduro\collision\src\Adapters\Laravel\IgnitionSolutionsRepository.php(36): Facade\Ignition\SolutionProviders\SolutionProviderRepository->getSolutionsForThrowable(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#10 C:\xampp\htdocs\inventory-test\vendor\nunomaduro\collision\src\Writer.php(244): NunoMaduro\Collision\Adapters\Laravel\IgnitionSolutionsRepository->getFromThrowable(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#11 C:\xampp\htdocs\inventory-test\vendor\nunomaduro\collision\src\Writer.php(123): NunoMaduro\Collision\Writer->renderSolution(Object(NunoMaduro\Collision\Adapters\Laravel\Inspector))
#12 C:\xampp\htdocs\inventory-test\vendor\nunomaduro\collision\src\Handler.php(39): NunoMaduro\Collision\Writer->write(Object(NunoMaduro\Collision\Adapters\Laravel\Inspector))
#13 C:\xampp\htdocs\inventory-test\vendor\nunomaduro\collision\src\Adapters\Laravel\ExceptionHandler.php(72): NunoMaduro\Collision\Handler->handle()      
#14 C:\xampp\htdocs\inventory-test\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(185): NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler->renderForConsole(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Symfony\Component\ErrorHandler\Error\FatalError))
#15 C:\xampp\htdocs\inventory-test\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(171): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#16 C:\xampp\htdocs\inventory-test\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(209): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#17 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#18 {main}
  thrown in C:\xampp\htdocs\inventory-test\vendor\facade\ignition\src\SolutionProviders\MergeConflictSolutionProvider.php on line 52
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255



PHP: 8.2
Laravel: 8.x

**Comment by SherAdnanKhan** [comment]
Don't use this, this package is deprecated.
